# Generated by Django 4.2 on 2024-02-27 18:03

from django.db import migrations, models
# from datetime import date


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('assignTo', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                # ('date', models.DateField(default=date.today))
            ],
        ),
    ]
